stages:
  train:
    cmd: PYTHONPATH=. python scripts/train.py
    deps:
    - data/mnist_data.npz
    - scripts/train.py
    - src/
    params:
    - train.batch_size
    - train.epochs
    - train.learning_rate
    outs:
    - logs/history_logs.csv
    - mnist_model.h5
  evaluate:
    cmd: PYTHONPATH=. python scripts/evaluate.py
    deps:
    - mnist_model.h5
    - scripts/evaluate.py
    - src/data/data.py
    - src/models/evaluate_utils.py
    outs:
    - logs/metrics.json
