stages:
  train:
    cmd: python main.py
    deps:
    - data.py
    - mnist_data.npz
    - model.py
    - train.py
    params:
    - train.batch_size
    - train.epochs
    - train.learning_rate
    outs:
    - history_logs.csv
    - mnist_model.h5
